import type { Printer, PrintRequest } from './types'

export const printers: Printer[] = [
  {
    id: '1',
    owner_id: 'owner-1',
    name: "Dave's Print Station",
    description:
      'Fast, reliable FDM printing for everyday items and functional parts. All prints are quality-checked before pickup.',
    printer_model: 'Bambu Lab X1C',
    print_types: ['everyday', 'strong', 'colorful'],
    materials: ['pla', 'petg', 'abs', 'tpu'],
    max_size: 'medium',
    price_min: 10,
    price_max: 80,
    turnaround: '1–2 days',
    contact_phone: '+60123456789',
    sample_photos: [],
    lat: 3.139,
    lng: 101.6869,
    available: true,
    rating: 4.8,
    review_count: 24,
    created_at: '2025-01-15T00:00:00Z',
    electricity_rate: null,
    filament_costs: null,
    markup_percent: null,
    power_watts: null,
    grams_per_roll: null,
    bed_type: null,
  },
  {
    id: '2',
    owner_id: 'owner-2',
    name: 'Quick Prints KL',
    description:
      'Budget-friendly prints for hobbyists and makers. Great quality at an affordable price. Perfect for prototypes.',
    printer_model: 'Prusa MK4S',
    print_types: ['everyday'],
    materials: ['pla', 'petg', 'tpu'],
    max_size: 'medium',
    price_min: 8,
    price_max: 60,
    turnaround: '2–3 days',
    contact_phone: '+60129876543',
    sample_photos: [],
    lat: 3.158,
    lng: 101.712,
    available: true,
    rating: 4.5,
    review_count: 62,
    created_at: '2025-02-03T00:00:00Z',
    electricity_rate: null,
    filament_costs: null,
    markup_percent: null,
    power_watts: null,
    grams_per_roll: null,
    bed_type: null,
  },
  {
    id: '3',
    owner_id: 'owner-3',
    name: 'Precision Parts Lab',
    description:
      'Engineering-grade prints with tight tolerances. Specializing in mechanical parts, enclosures, and structural components.',
    printer_model: 'Bambu Lab X1C AMS',
    print_types: ['strong', 'colorful'],
    materials: ['pla', 'petg', 'abs', 'nylon'],
    max_size: 'medium',
    price_min: 20,
    price_max: 150,
    turnaround: '2–4 days',
    contact_phone: '+60112233445',
    sample_photos: [],
    lat: 3.09,
    lng: 101.674,
    available: true,
    rating: 4.9,
    review_count: 29,
    created_at: '2025-03-05T00:00:00Z',
    electricity_rate: null,
    filament_costs: null,
    markup_percent: null,
    power_watts: null,
    grams_per_roll: null,
    bed_type: null,
  },
  {
    id: '4',
    owner_id: 'owner-4',
    name: 'ColorPop 3D',
    description:
      'Specializing in vibrant multi-color prints for art, decor, and custom designs. Makes your ideas come alive in color.',
    printer_model: 'Bambu Lab P1S AMS',
    print_types: ['everyday', 'colorful'],
    materials: ['pla', 'petg'],
    max_size: 'medium',
    price_min: 15,
    price_max: 120,
    turnaround: '2–3 days',
    contact_phone: '+60134455667',
    sample_photos: [],
    lat: 3.172,
    lng: 101.708,
    available: false,
    rating: 4.6,
    review_count: 35,
    created_at: '2025-02-28T00:00:00Z',
    electricity_rate: null,
    filament_costs: null,
    markup_percent: null,
    power_watts: null,
    grams_per_roll: null,
    bed_type: null,
  },
  {
    id: '5',
    owner_id: 'owner-5',
    name: 'MakerSpace Print Hub',
    description:
      'Flexible printing service for all kinds of projects. TPU and standard filaments available. Fast turnaround guaranteed.',
    printer_model: 'Creality K1C',
    print_types: ['everyday', 'strong'],
    materials: ['pla', 'petg', 'tpu'],
    max_size: 'small',
    price_min: 5,
    price_max: 50,
    turnaround: '1–2 days',
    contact_phone: '+60145566778',
    sample_photos: [],
    lat: 3.145,
    lng: 101.72,
    available: true,
    rating: 4.4,
    review_count: 18,
    created_at: '2025-03-10T00:00:00Z',
    electricity_rate: null,
    filament_costs: null,
    markup_percent: null,
    power_watts: null,
    grams_per_roll: null,
    bed_type: null,
  },
  {
    id: '6',
    owner_id: 'owner-6',
    name: 'BigBuild Studio',
    description:
      'Large format printing for oversized projects. Perfect for cosplay props, display models, and architectural pieces.',
    printer_model: 'Creality CR-10 Smart Pro',
    print_types: ['everyday', 'strong'],
    materials: ['pla', 'petg', 'abs', 'nylon'],
    max_size: 'large',
    price_min: 25,
    price_max: 200,
    turnaround: '3–5 days',
    contact_phone: '+60156677889',
    sample_photos: [],
    lat: 3.11,
    lng: 101.65,
    available: true,
    rating: 4.7,
    review_count: 12,
    created_at: '2025-03-20T00:00:00Z',
    electricity_rate: null,
    filament_costs: null,
    markup_percent: null,
    power_watts: null,
    grams_per_roll: null,
    bed_type: null,
  },
]

export const mockRequests: PrintRequest[] = [
  {
    id: 'req-1',
    printer_id: '1',
    customer_name: 'Ahmad Farid',
    customer_email: 'ahmad@example.com',
    customer_phone: '+60187654321',
    description: 'I need a custom phone stand for my desk. Something minimal and clean.',
    model_url: null,
    model_title: null,
    model_image: null,
    file_url: null,
    stl_url: null,
    stl_urls: [],
    gcode_urls: [],
    plate_filaments: [],
    color_preferences: [],
    weight_g: null,
    print_hours: null,
    print_type: 'everyday',
    material: 'pla',
    color: 'Black',
    color_hex: '#222222',
    supports: false,
    size: 'small',
    quality: 'standard',
    deadline: '2026-05-15',
    notes: 'Prefer black or dark grey color if possible.',
    profile_id: null,
    selected_addons: [],
    status: 'new',
    quoted_price: null,
    quoted_by_date: null,
    quote_message: null,
    created_at: '2026-05-11T08:30:00Z',
  },
  {
    id: 'req-2',
    printer_id: '1',
    customer_name: 'Sarah Lim',
    customer_email: 'sarah@example.com',
    customer_phone: '+60198765432',
    description: 'Need a replacement bracket for my CCTV camera mount. The original broke.',
    model_url: null,
    model_title: null,
    model_image: null,
    file_url: 'https://example.com/bracket.stl',
    stl_url: null,
    stl_urls: [],
    gcode_urls: [],
    plate_filaments: [],
    color_preferences: [],
    weight_g: null,
    print_hours: null,
    print_type: 'strong',
    material: 'nylon',
    color: 'Natural',
    color_hex: '#e8e0d0',
    supports: false,
    size: 'small',
    quality: 'standard',
    deadline: '2026-05-13',
    notes: 'Must be strong enough to hold a 500g camera.',
    profile_id: null,
    selected_addons: [],
    status: 'quoted',
    quoted_price: 35,
    quoted_by_date: '2026-05-13',
    quote_message: 'I can print this in PETG for strength. Ready by Wednesday.',
    created_at: '2026-05-10T14:00:00Z',
  },
  {
    id: 'req-3',
    printer_id: '1',
    customer_name: 'Raj Kumar',
    customer_email: 'raj@example.com',
    customer_phone: '+60161234567',
    description: 'Custom gear for a robotics project. Need 3 identical pieces.',
    model_url: null,
    model_title: null,
    model_image: null,
    file_url: 'https://example.com/gear.stl',
    stl_url: null,
    stl_urls: [],
    gcode_urls: [],
    plate_filaments: [],
    color_preferences: [],
    weight_g: null,
    print_hours: null,
    print_type: 'strong',
    material: 'nylon',
    color: 'Natural',
    color_hex: '#e8e0d0',
    supports: true,
    size: 'small',
    quality: 'premium',
    deadline: '2026-05-18',
    notes: '3 identical copies. Tight tolerance needed.',
    profile_id: null,
    selected_addons: [],
    status: 'printing',
    quoted_price: 65,
    quoted_by_date: '2026-05-17',
    quote_message: 'Will print in Nylon for durability. 3 copies at RM65 total.',
    created_at: '2026-05-09T10:00:00Z',
  },
  {
    id: 'req-4',
    printer_id: '1',
    customer_name: 'Wei Lin',
    customer_email: 'wei@example.com',
    customer_phone: '+60172345678',
    description: 'Small figurine of my dog as a gift.',
    model_url: null,
    model_title: null,
    model_image: null,
    file_url: null,
    stl_url: null,
    stl_urls: [],
    gcode_urls: [],
    plate_filaments: [],
    color_preferences: [],
    weight_g: null,
    print_hours: null,
    print_type: 'everyday',
    material: 'pla',
    color: 'White',
    color_hex: '#f5f5f5',
    supports: false,
    size: 'small',
    quality: 'premium',
    deadline: '2026-05-08',
    notes: 'I will send a photo of my dog.',
    profile_id: null,
    selected_addons: [],
    status: 'collected',
    quoted_price: 45,
    quoted_by_date: '2026-05-07',
    quote_message: 'Printed in white PLA, high detail. Looks great!',
    created_at: '2026-05-05T09:00:00Z',
  },
]

export function getPrinterById(id: string): Printer | undefined {
  return printers.find((p) => p.id === id)
}

export function getRequestsByPrinterId(printerId: string): PrintRequest[] {
  return mockRequests.filter((r) => r.printer_id === printerId)
}

export function haversineDistance(
  lat1: number,
  lng1: number,
  lat2: number,
  lng2: number,
): number {
  const R = 6371
  const dLat = ((lat2 - lat1) * Math.PI) / 180
  const dLng = ((lng2 - lng1) * Math.PI) / 180
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) ** 2
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
}
