export interface GcodeStats {
  weight_g:    number | null
  print_hours: number | null
  layer_count: number | null
  slicer:      string | null
}

// Read only the header (first 60 KB) and footer (last 30 KB) of a gcode file —
// all slicer-embedded stats are written in those regions.
export async function parseGcodeFile(file: File): Promise<GcodeStats> {
  const HEAD = 61_440   // 60 KB
  const TAIL = 30_720   // 30 KB
  const [headText, tailText] = await Promise.all([
    file.slice(0, HEAD).text(),
    file.slice(Math.max(0, file.size - TAIL)).text(),
  ])
  return parseGcodeText(`${headText}\n${tailText}`)
}

export function parseGcodeText(content: string): GcodeStats {
  let weight_g:    number | null = null
  let print_hours: number | null = null
  let layer_count: number | null = null
  let slicer:      string | null = null

  for (const raw of content.split('\n')) {
    const line = raw.trim()
    if (!line.startsWith(';')) continue

    if (!slicer) {
      if (/generated by PrusaSlicer/i.test(line))      slicer = 'PrusaSlicer'
      else if (/generated by SuperSlicer/i.test(line)) slicer = 'SuperSlicer'
      else if (/generated by BambuStudio/i.test(line)) slicer = 'BambuStudio'
      else if (/Generated with Cura/i.test(line))      slicer = 'Cura'
      else if (/Sliced by ideaMaker/i.test(line))      slicer = 'IdeaMaker'
      else if (/Simplify3D/i.test(line))               slicer = 'Simplify3D'
    }

    if (weight_g === null) {
      const mTotal = line.match(/;\s*total\s+filament\s+used\s*\[g\]\s*=\s*([\d.]+)/i)
      if (mTotal) { weight_g = parseFloat(mTotal[1]); continue }
      const mG = line.match(/;\s*filament\s+used\s*\[g\]\s*=\s*([\d.]+)/i)
      if (mG) { weight_g = parseFloat(mG[1]); continue }
      const mW = line.match(/;\s*filament\s+weight\s*[=:]\s*([\d.]+)\s*g?/i)
      if (mW) { weight_g = parseFloat(mW[1]); continue }
      // Cura: meters → grams (1.75mm PLA ~2.98 g/m)
      const mM = line.match(/;Filament\s+used\s*:\s*([\d.]+)\s*m\b/i)
      if (mM) { weight_g = Math.round(parseFloat(mM[1]) * 2.98 * 10) / 10; continue }
    }

    if (print_hours === null) {
      const mPrusa = line.match(/;\s*estimated\s+printing\s+time(?:\s*\([^)]*\))?\s*=\s*(.+)/i)
      if (mPrusa) { print_hours = toHours(parseTimeStr(mPrusa[1])); continue }
      const mPrintTime = line.match(/;PRINT\.TIME\s*:\s*(\d+)/i)
      if (mPrintTime) { print_hours = toHours(parseInt(mPrintTime[1]) / 3600); continue }
      const mTime = line.match(/^;TIME\s*:\s*(\d+)$/i)
      if (mTime) { print_hours = toHours(parseInt(mTime[1]) / 3600); continue }
      const mBuild = line.match(/;\s*Build\s+time\s*:\s*(.+)/i)
      if (mBuild) { print_hours = toHours(parseTimeStr(mBuild[1])); continue }
    }

    if (layer_count === null) {
      const mLC = line.match(/;\s*layer_count\s*=\s*(\d+)/i)
               ?? line.match(/;Layer\s+count\s*:\s*(\d+)/i)
      if (mLC) { layer_count = parseInt(mLC[1]); continue }
    }
  }

  return { weight_g, print_hours, layer_count, slicer }
}

function parseTimeStr(s: string): number {
  let secs = 0
  const h   = s.match(/(\d+)\s*h/i)
  const m   = s.match(/(\d+)\s*m(?!s)/i)
  const sec = s.match(/(\d+)\s*s/i)
  if (h)   secs += parseInt(h[1]) * 3600
  if (m)   secs += parseInt(m[1]) * 60
  if (sec) secs += parseInt(sec[1])
  return secs / 3600
}

function toHours(h: number): number {
  return Math.round(h * 10) / 10
}
