import { NextRequest, NextResponse } from 'next/server'

export async function GET(req: NextRequest) {
  const url = req.nextUrl.searchParams.get('url')
  if (!url) return NextResponse.json({ error: 'No URL' }, { status: 400 })

  try {
    // PrusaSlicer writes "; estimated printing time" at the end of its settings header,
    // which can be 20-50KB into the file. Fetch 60KB to reliably catch it.
    // Filament weight is written at the very end — 30KB covers that for all slicers.
    const [start, end] = await Promise.all([
      fetchBytes(url, 'bytes=0-61439'),   // first 60KB
      fetchBytes(url, 'bytes=-30719'),    // last 30KB
    ])
    const text = `${start ?? ''}\n${end ?? ''}`
    if (!text.trim()) return NextResponse.json({ error: 'Empty file' }, { status: 422 })
    return NextResponse.json(parseGcode(text))
  } catch {
    return NextResponse.json({ error: 'Failed to read file' }, { status: 500 })
  }
}

async function fetchBytes(url: string, range: string): Promise<string | null> {
  try {
    const res = await fetch(url, {
      headers: { Range: range },
      signal: AbortSignal.timeout(12000),
    })
    if (res.status === 416) {
      // File smaller than range — read whole file
      const full = await fetch(url, { signal: AbortSignal.timeout(12000) })
      return full.ok ? full.text() : null
    }
    return res.ok ? res.text() : null
  } catch { return null }
}

interface GcodeStats {
  weight_g: number | null
  print_hours: number | null
  layer_count: number | null
  slicer: string | null
}

function parseGcode(content: string): GcodeStats {
  let weight_g: number | null = null
  let print_hours: number | null = null
  let layer_count: number | null = null
  let slicer: string | null = null

  for (const raw of content.split('\n')) {
    const line = raw.trim()
    if (!line.startsWith(';')) continue

    // ── Slicer detection ──────────────────────────────────────────────
    if (!slicer) {
      if (/generated by PrusaSlicer/i.test(line))      slicer = 'PrusaSlicer'
      else if (/generated by SuperSlicer/i.test(line)) slicer = 'SuperSlicer'
      else if (/generated by BambuStudio/i.test(line)) slicer = 'BambuStudio'
      else if (/Generated with Cura/i.test(line))      slicer = 'Cura'
      else if (/Sliced by ideaMaker/i.test(line))      slicer = 'IdeaMaker'
      else if (/Simplify3D/i.test(line))               slicer = 'Simplify3D'
    }

    // ── Filament weight (grams) ───────────────────────────────────────
    if (weight_g === null) {
      // PrusaSlicer / Bambu: "; total filament used [g] = 24.51"
      // Prefer "total" (multi-extruder) over per-extruder entries
      const mTotal = line.match(/;\s*total\s+filament\s+used\s*\[g\]\s*=\s*([\d.]+)/i)
      if (mTotal) { weight_g = parseFloat(mTotal[1]); continue }

      const mG = line.match(/;\s*filament\s+used\s*\[g\]\s*=\s*([\d.]+)/i)
      if (mG) { weight_g = parseFloat(mG[1]); continue }

      // Simplify3D / generic: "; Filament weight: 13.53 g"
      const mW = line.match(/;\s*filament\s+weight\s*[=:]\s*([\d.]+)\s*g?/i)
      if (mW) { weight_g = parseFloat(mW[1]); continue }

      // Cura: ";Filament used: 3.45m" — convert meters → grams (1.75mm filament, ~3g/m for PLA)
      const mM = line.match(/;Filament\s+used\s*:\s*([\d.]+)\s*m\b/i)
      if (mM) { weight_g = Math.round(parseFloat(mM[1]) * 2.98 * 10) / 10; continue }
    }

    // ── Print time ────────────────────────────────────────────────────
    if (print_hours === null) {
      // PrusaSlicer / Bambu: "; estimated printing time (normal mode) = 1h 23m 4s"
      const mPrusa = line.match(/;\s*estimated\s+printing\s+time(?:\s*\([^)]*\))?\s*=\s*(.+)/i)
      if (mPrusa) { print_hours = toHours(parseTimeString(mPrusa[1])); continue }

      // Cura newer: ";PRINT.TIME:8040"
      const mPrintTime = line.match(/;PRINT\.TIME\s*:\s*(\d+)/i)
      if (mPrintTime) { print_hours = toHours(parseInt(mPrintTime[1]) / 3600); continue }

      // Cura: ";TIME:8040" (seconds)
      const mTime = line.match(/^;TIME\s*:\s*(\d+)$/i)
      if (mTime) { print_hours = toHours(parseInt(mTime[1]) / 3600); continue }

      // Simplify3D: "; Build time: 2 hours 14 minutes"
      const mBuild = line.match(/;\s*Build\s+time\s*:\s*(.+)/i)
      if (mBuild) { print_hours = toHours(parseTimeString(mBuild[1])); continue }
    }

    // ── Layer count ───────────────────────────────────────────────────
    if (layer_count === null) {
      const mLC = line.match(/;\s*layer_count\s*=\s*(\d+)/i)        // PrusaSlicer
              ?? line.match(/;Layer\s+count\s*:\s*(\d+)/i)           // Cura
      if (mLC) { layer_count = parseInt(mLC[1]); continue }
    }
  }

  return { weight_g, print_hours, layer_count, slicer }
}

// Parse "1h 23m 4s", "2 hours 14 minutes", "84 minutes" → hours as float
function parseTimeString(s: string): number {
  let secs = 0
  const h   = s.match(/(\d+)\s*h/i)
  const m   = s.match(/(\d+)\s*m(?!s)/i)
  const sec = s.match(/(\d+)\s*s/i)
  if (h)   secs += parseInt(h[1]) * 3600
  if (m)   secs += parseInt(m[1]) * 60
  if (sec) secs += parseInt(sec[1])
  return secs / 3600
}

function toHours(h: number): number {
  return Math.round(h * 10) / 10
}
